name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ghcr.io Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/app:latest
